import { registerAs } from '@nestjs/config'

export default registerAs(
	'websites',
	() =>
		<any>{
			CRON_WEBSITES_WEBSITE_SCREENSHOT_GENERATE: process.env.CRON_WEBSITES_WEBSITE_SCREENSHOT_GENERATE,
			CRON_WEBSITES_WEBSITE_SCREENSHOT_GENERATE_FREQUENCY:
				process.env.CRON_WEBSITES_WEBSITE_SCREENSHOT_GENERATE_FREQUENCY,
			CRON_WEBSITES_WEBSITE_ICON_GENERATE: process.env.CRON_WEBSITES_WEBSITE_ICON_GENERATE,
			CRON_WEBSITES_WEBSITE_ICON_GENERATE_FREQUENCY: process.env.CRON_WEBSITES_WEBSITE_ICON_GENERATE_FREQUENCY,
		},
)
