import { EverflowClick } from './everflow.click.dto'
import { faker } from '@faker-js/faker'
import { EverflowOffer } from '../offer/offer.dto'

export function mockClick(offer: EverflowOffer): EverflowClick {
	return {
		transaction_id: faker.string.alphanumeric({ length: 32 }),
		is_unique: Number(faker.number.binary()),
		unix_timestamp: new Date(faker.date.recent()).getTime(),
		tracking_url: faker.internet.url(),
		source_id: faker.number.bigInt().toString(),
		sub1: faker.lorem.word(),
		sub2: faker.commerce.product(),
		sub3: faker.commerce.productName(),
		sub4: faker.company.name(),
		sub5: faker.internet.url(),
		revenue_type: 'CPS',
		revenue: 0,
		referer: faker.internet.url(),
		error_code: 0,
		user_ip: faker.internet.ip(),
		error_message: 'N/A',
		idfa: '',
		idfa_md5: '',
		idfa_sha1: '',
		google_ad_id: '',
		google_ad_id_md5: '',
		google_ad_id_sha1: '',
		android_id: '',
		android_id_md5: '',
		android_id_sha1: '',
		relationship: {
			offer: {
				network_offer_id: offer.network_offer_id,
				network_id: offer.network_id,
				name: offer.name,
				offer_status: offer.offer_status,
				network_tracking_domain_id: offer.network_tracking_domain_id,
			},
			geolocation: {
				country_code: faker.location.countryCode(),
				country_name: faker.location.country(),
				region_code: '',
				region_name: faker.location.state(),
				city_name: faker.location.city(),
				dma: faker.number.int({ min: 1, max: 999 }),
				dma_name: 'Greenville-Spartanburg, SC-Asheville, NC-Anderson, SC',
				timezone: faker.location.timeZone(),
				carrier_name: '',
				carrier_code: 0,
				organization: '',
				isp_name: 'Horizon',
				is_mobile: Boolean(faker.number.binary()),
				is_proxy: Boolean(faker.number.binary()),
				postal_code: faker.location.zipCode(),
			},
			device_information: {
				is_mobile: Boolean(faker.number.binary()),
				platform_name: 'macOS',
				os_version: '10.15',
				brand: 'Apple',
				model: '',
				is_tablet: Boolean(faker.number.binary()),
				browser_name: 'Safari',
				browser_version: '',
				device_type: 'PC',
				language: 'en',
				http_accept_language: '',
				is_robot: false,
				is_filter: false,
			},
			query_parameters: {
				foo: 'bar',
			},
		},
		currency_id: 'USD',
	}
}
