export enum Integrations {
    BUFFER = 'Buffer',
    CREATIFY = 'Creatify',
    DATAFORSEO = 'DataforSEO',
    EVERFLOW = 'Everflow',
    GOOGLE_SHEETS = 'Google Sheets',
    GOOGLE_ANALYTICS = 'Google Analytics',
    KLAVIYO = 'Klaviyo',
    OPENAI = 'Openai',
    RECHARGE = 'Recharge',
    SHIPBOB = 'Shipbob',
    SHOPIFY = 'Shopify',
    SLACK = 'Slack', 
    SPYFU = 'Spyfu',
}