import { faker } from '@faker-js/faker'
import { EverflowOffer } from '../offer/offer.dto'
import { EverflowConversion } from './conversion.dto'

export function mockConversion(offer: EverflowOffer): EverflowConversion {
	return {
		conversion_id: faker.string.alphanumeric({ length: 32 }),
		conversion_unix_timestamp: new Date(faker.date.recent()).getTime(),
		sub1: faker.lorem.word(),
		sub2: faker.commerce.product(),
		sub3: faker.commerce.productName(),
		sub4: faker.company.name(),
		sub5: faker.internet.url(),
		source_id: faker.number.bigInt().toString(),
		revenue_type: 'CPS',
		revenue: faker.number.float({ min: 3, max: 199 }),
		session_user_ip: faker.internet.ip(),
		conversion_user_ip: faker.internet.ip(),
		country: faker.location.country(),
		region: faker.location.state(),
		city: faker.location.city(),
		dma: faker.number.int({ min: 1, max: 999 }),
		carrier: '',
		platform: 'iOS',
		os_version: '16.1',
		device_type: 'Mobile',
		brand: 'Apple',
		browser: 'Chrome',
		language: 'en',
		http_user_agent:
			'Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/116.0.5845.118 Mobile/15E148 Safari/604.1',
		is_event: false,
		event: 'Purchase',
		transaction_id: faker.string.alphanumeric({ length: 32 }),
		click_unix_timestamp: new Date(faker.date.past()).getTime(),
		isp: 'horizon',
		referer: faker.internet.url(),
		app_id: '',
		idfa: '',
		idfa_md5: '',
		idfa_sha1: '',
		google_ad_id: '',
		google_ad_id_md5: '',
		google_ad_id_sha1: '',
		android_id: '',
		android_id_md5: '',
		android_id_sha1: '',
		currency_id: 'USD',
		is_view_through: false,
		order_id: faker.number.bigInt().toString(),
		adv1: '',
		adv2: '',
		adv3: '',
		adv4: '',
		adv5: '',
		relationship: {
			offer: {
				network_offer_id: offer.network_offer_id,
				network_id: offer.network_id,
				name: offer.name,
				offer_status: offer.offer_status,
				network_tracking_domain_id: offer.network_tracking_domain_id,
			},
			events_count: 0,
		},
		sale_amount: faker.number.float({ min: 9, max: 299 }),
	}
}
