export declare class Countries {
    static convertISO2ToISO3(iso2: string): string;
    static countryNameToISO2(countryName: any): string;
    static getCountry(ISO2: any): {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": string;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": number;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": string;
        GeoNameID: number;
        E164: number;
        "Phone Code": string;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": string;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": number;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": string;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: string;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": string;
        GeoNameID: number;
        E164: number;
        "Phone Code": string;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": number;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": number;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": number;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: string;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": string;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: string;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": string;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": string;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": string;
        "Internet Users": string;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": string;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": number;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: string;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": string;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: string;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: string;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": string;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: string;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": number;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": string;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": string;
        "Internet Users": number;
        "Phones (Mobile)": number;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": number;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": number;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": string;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": string;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: number;
    } | {
        "Country Name": string;
        ISO2: string;
        ISO3: string;
        "Top Level Domain": string;
        FIPS: string;
        "ISO Numeric": number;
        GeoNameID: number;
        E164: number;
        "Phone Code": string;
        Continent: string;
        Capital: string;
        "Time Zone in Capital": string;
        Currency: string;
        "Language Codes": string;
        Languages: string;
        "Area KM2": number;
        "Internet Hosts": number;
        "Internet Users": string;
        "Phones (Mobile)": string;
        "Phones (Landline)": string;
        GDP: string;
    };
}
