#!/usr/bin/env bash
set -e
. "$JL_WORKDIR/common"

cli_help() {
  echo "
Command: pr

Use: Operations for Pull Requests

Options:
  list 		- List Pull Requests
  checkout 	- Checkout a Pull Request
  view 		- View a Pull Request

Example: JL pr list
Example: JL pr checkout
Example: JL pr view
"
exit 1
}

[ ! -n "$1" ] && cli_help

cli_log "PR"

case "$1" in
  list|d)

        cli_log "List Pull Requests"
#       LIST=$(gh pr list)
#        echo $LIST
#        DONE=$(ipt $LIST)

echo $DONE
        cli_log_error "TODO: way of selecting a PR to checkout or view"

        ;;
  checkout|d)

		echo "Specify the pull request ID: [<number>]"
        read PR_ID
        export PR_ID

  		cli_log "Checkout Pull Request: $PR_ID"
  		gh pr checkout $PR_ID

        ;;
  view|d)

		echo "Specify the pull request ID: [<number>]"
        read PR_ID
        export PR_ID

  		cli_log "View Pull Request: $PR_ID"
  		gh pr view $PR_ID

        ;;
  *)
    cli_help
    ;;
esac

cli_log "END"